const posts = [
    {
        id:1,
        title: "Every Black Hole Contains Another Universe?",
        category: "Science",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "John Doe",
        date: "2019.06.10",
        views: 12,
        image: "images/universe.jpg",
    },
    {
        id:2,
        title: "Eight amazing Canadian road trips",
        category: "Travel",
        author: "John Doe",
        views: 45,
        date: "2019.08.10",
        image: "images/canadian.jpg",
    },
    {
        id:3,
        title: "Google and BBC scrap VR projects",
        category: "Tech",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "John Doe",
        date: "2019.18.09",
        views: 13,
        image: "images/vr.jpg",
    },
    {
        id:4,
        title: "The five most creative cities",
        category: "Travel",
        author: "John Doe",
        date: "2019.10.10",
        views: 67,
        image: "images/city.jpg",
    },
    {
        id:5,
        title: "The most important part of Versailles",
        category: "Art",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Mary Linn",
        views: 10,
        date: "2019.18.08",
        image: "images/Versal.jpg",
    },
    {
        id:6,
        title: "A simple guide to protecting your privacy online",
        category: "Tech",
        author: "John Doe",
        views: 60,
        date: "2019.07.10",
        image: "images/online.jpeg",
    },
    {
        id:7,
        title: "Lithium-ion batteries take chemistry Nobel",
        category: "Science",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Dann Wright",
        date: "2019.27.10",
        views: 18,
        image: "images/battery.jpg",
    },
    {
        id:8,
        title: "A local's guide to Vancouver",
        category: "Travel",
        author: "John Doe",
        views: 34,
        date: "2019.06.10",
        image: "images/vancouver.jpg",
    },
    {
        id:9,
        title: "These are the world’s best stargazing spots",
        category: "Travel",
        author: "John Doe",
        views: 37,
        date: "2019.07.10",
        image: "images/stars.jpg",
    },
    {
        id:10,
        title: "How life blossomed after the dinosaurs died",
        category: "Science",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Dann Wright",
        date: "2019.07.10",
        views: 3,
        image: "images/dino.jpg",
    },
    {
        id:11,
        title: "Is this the world's scariest island",
        category: "Science",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Dann Wright",
        date: "2019.10.19",
        views: 1,
        image: "images/volcano.jpg",
    },
    {
        id: 12,
        title: "SpaceX has unveiled the rocket it hopes will one day carry humans to Mars",
        category: "science",
        date: "2019.11.04",
        image: "/images/spacex.jpg",
    },
    {
        id: 13,
        title: "What’s it like to live in an over-touristed city?",
        category: "travel",
        date: "2019.11.03",
        image: "/images/Prague.jpg",
    },
    {
        id: 14,
        title: "What will art look like in 20 years",
        category: "art",
        date: "2019.11.02",
        image: "images/p076x7tm.jpg",
    },
    {
        id: 15,
        title: "Why aren't we living longer?",
        category: "health",
        date: "2019.11.01",
        image: "images/eyes.jpg",
    },
    {
        id: 16,
        title: "Facebook removes hundreds of 'inauthentic accounts'",
        category: "tech",
        date: "2019.10.10",
        image: "images/fb.jpg",
    },

]
export default posts