const posts = [
    {
        id:1,
        title: "Every Black Hole Contains Another Universe?",
        category: "Science",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Author",
        date: "2019.06.10",
        views: 12,
        image: "images/universe.jpg",
    },
    {
        id:2,
        title: "Eight amazing Canadian road trips",
        category: "Travel",
        author: "Author",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        views: 45,
        date: "2019.08.10",
        image: "images/canadian.jpg",
    },
    {
        id:3,
        title: "Google and BBC scrap VR projects",
        category: "Tech",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Author",
        date: "2019.09.18",
        views: 13,
        image: "images/vr.jpg",
    },
    {
        id:4,
        title: "The five most creative cities",
        category: "Travel",
        author: "Author",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        date: "2019.10.10",
        views: 67,
        image: "images/city.jpg",
    },
    {
        id:5,
        title: "Boston Dynamics boss learned by unbalancing toddler",
        category: "Tech",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Author",
        views: 12,
        date: "2019.11.07",
        image: "images/spot.jpg",
    },
    {
        id:6,
        title: "These are the world’s best stargazing spots",
        category: "Travel",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Author",
        views: 29,
        date: "2019.11.08",
        image: "images/stars.jpg",
    },
    {
        id:7,
        title: "A local's guide to Vancouver",
        category: "Travel",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Author",
        views: 34,
        date: "2019.11.09",
        image: "images/vancouver.jpg",
    },
    {
        id:8,
        title: "Daylight Saving Time: ‘Falling Back’ Can Increase Seasonal Depression",
        category: "Health",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Author",
        date: "2019.11.09",
        views: 18,
        image: "images/depression.jpg",
    },
    {
        id:9,
        title: "How life blossomed after the dinosaurs died",
        category: "Science",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Author",
        date: "2019.07.10",
        views: 35,
        image: "images/dino.jpg",
    },
    {
        id:10,
        title: "Is this the world's scariest island",
        category: "Science",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Author",
        date: "2019.10.19",
        views: 35,
        image: "images/volcano.jpg",
    },
    {
        id: 11,
        title: "SpaceX has unveiled the rocket it hopes will one day carry humans to Mars",
        category: "Science",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Author",
        date: "2019.11.04",
        views: 23,
        image: "/images/spacex.jpg",
    },
    {
        id: 12,
        title: "What’s it like to live in an over-touristed city?",
        category: "Travel",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Author",
        date: "2019.11.03",
        views: 15,
        image: "/images/Prague.jpg",
    },
    {
        id: 13,
        title: "Bubonic plague: Third case reported in China",
        category: "Health",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Author",
        date: "2019.11.01",
        views: 16,
        image: "images/flea-drawing.jpg",
    },
    {
        id: 14,
        title: "Facebook removes hundreds of 'inauthentic accounts'",
        category: "Tech",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Author",
        date: "2019.10.10",
        views: 13,
        image: "images/fb.jpg",
    },
    {
        id: 15,
        title: "Drug-resistant superbug kills someone every 15 minutes",
        category: "Health",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Author",
        date: "2019.09.22",
        views: 13,
        image: "images/superbug.jpg",
    },
    {
        id: 16,
        title: "Exercising before breakfast burns more fat, study says",
        category: "Health",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Author",
        date: "2019.10.21",
        views: 13,
        image: "images/fitness.jpg",
    },
    {
        id: 17,
        title: "Google’s AI-powered Smart Compose feature is coming to Docs",
        category: "Tech",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere sequi magnam eum id reprehe quisquam debitis assumenda eos minima, itaque consequatur voluptates, nihil quos repudiandae? Qnecessitatibus perspiciatis consequatur veniam!",
        author: "Author",
        date: "2019.10.18",
        views: 13,
        image: "images/docs.jpg",
    },
    

]
export default posts